In [31]:
import pandas as pd

ls = [5,11,14,30,33,38,24]
s = pd.Series(ls, index=[1,2,3,4,5,6,'bonus'])
s

1         5
2        11
3        14
4        30
5        33
6        38
bonus    24
dtype: int64

In [77]:
jumsu = {
    '홍길동' : [50,60,50],
    '이순신' : [60,60,60],
    '강감찬' : [100,90,90],
    '유관순' : [80,80,90],
    '강환석' : [95,95,95],
}

for i in range(5):
    name = list(jumsu.keys())[i]
    print(f"-{name}-", end='-')
print()
for i in range(5):
    score = list(jumsu.values())[i]
    avg = round(sum(score)/len(score),2)
    print(f"-{avg}점-", end='-')


-홍길동---이순신---강감찬---유관순---강환석--
-53.33점---60.0점---93.33점---83.33점---95.0점--

In [78]:
# 071일차-실습-0-2-해답 
import numpy as np
import time
from datetime import datetime, date
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
#
jumsu = {
'홍길동' : [50,60,50],
'이순신' : [60,60,60],
'강감찬' : [100,90,90],
'유관순' : [80,80,90],
'강환석' : [95,95,95],
}
s1_jumsu = pd.Series(jumsu)
for i in s1_jumsu.index:
    print('-' + i + '-', end='-')
print()
for i in s1_jumsu.values:
    #print(i)
    #print(type(i))
    print( '-{:.2f}점-'.format( np.mean(i)), end='')  
        # np는 numpy 라이브러리를 말함 np.mean()은 평균 함수임

-홍길동---이순신---강감찬---유관순---강환석--
-53.33점--60.00점--93.33점--83.33점--95.00점-

In [84]:
import numpy as np
import pandas as pd 
#
jumsu = {
'홍길동' : [50,60,50],
'이순신' : [60,60,60],
'강감찬' : [100,90,90],
'유관순' : [80,80,90],
'강환석' : [95,95,95],
}
s1_jumsu = pd.Series(jumsu)
for i in s1_jumsu.index:
    print('-' + i + '-', end='-')
print()
for i in s1_jumsu.values:
    #print(i)
    #print(type(i))
    print( '-{:.2f}점-'.format(np.max(i)), end='')  
print()
for i in s1_jumsu.values:
    #print(i)
    #print(type(i))
    print( '-{:.2f}점-'.format(np.min(i)), end='')  

-홍길동---이순신---강감찬---유관순---강환석--
-60.00점--60.00점--100.00점--90.00점--95.00점-
-50.00점--60.00점--90.00점--80.00점--95.00점-

In [142]:
jumsu = {
    '홍길동' : [50,60,50],
    '이순동' : [60,60,60],
    '강감동' : [100,90,90],
    '유관동' : [80,80,90],
    '홍길도' : [50,45,50],
    '이순도' : [80,70,66],
    '강감도' : [64,49,50],
    '유관도' : [60,50,50],
    '홍길재' : [50,45,51],
    '이순재' : [80,70,61],
    '강감재' : [64,49,51],
    '유관재' : [60,50,51],
    '강환석' : [95,95,95],
}

jumsu2 = dict(  {   key : round(np.mean(value),2)   for key, value  in jumsu.items() if np.mean(value)<60  } )
                                                                     # jumsu 딕셔너리의 밸류 중에서 평균이 60 미만인 것만 
                                                                     # 뽑아낸 쌍을 items() 튜플에 할당하고 튜플의 요소를 
                                                                     # unpacking하여 key, value 라는 변수에 할당하는 for문 
                                                                     # items() 함수는 Key와 Value의 쌍을 튜플로 묶은 값을 dict_items  
                                                                     # 객체로반환함. 이 구절에서는 튜플로 묶은 dict_items 객체를 
                                                                     # in 연산자 왼쪽의  key, value에 unpacking하였다
                           # for 문으로 발생한 key, value를 
                           # 각각 key와 round(np.mean(value),2)의 쌍으로 구성하고 이것을
                # dict() 형변환 함수로 변환하여 jumsu2 딕셔너리로 생성한다.
#
#print(type(jumsu2)) # 서비스 코드임
#print(jumsu2)       # 서비스 코드임
#
jumsu3 = pd.Series(jumsu2)
for i in jumsu3.index:
    print(i, end="-")
print()
for i in jumsu3:
    print(i, end="--")
print()

홍길동-홍길도-강감도-유관도-홍길재-강감재-유관재-
53.33--48.33--54.33--53.33--48.67--54.67--53.67--


In [153]:
#071일차-실습-0-5-해답.
# ndarray의 메서드 확인 
import numpy as np
num1 =0
for i in dir(np.ndarray) :
    if not i.startswith("_") :
        if type(np.ndarray.__dict__[i]) == type(np.ndarray.var)  :
            #print(i)
            num1 +=1
print('ndarray 메서드의 갯수',num1)
 
# 리스트 클래스의 메서드 확인 
num1=0
for i in dir('list') :
    if not i.startswith("_") :
        #print(i)
        num1 +=1
print('리스트 메서드의 갯수',num1)
 
import numpy as np
# ndarray의 속성(변수) 확인 
num1 =0
for i in dir(np.ndarray) :
    if not i.startswith("_") :
        if type(np.ndarray.__dict__[i]) != type(np.ndarray.var)  :
            #print(i)
            num1 +=1
print('ndarray 속성의 갯수',num1)
 
# 리스트 클래스의 속성 확인 
num1=0
for i in dir('list') :
    if i.startswith("_") :
        #print(i)
        num1 +=1
print('리스트 속성의 갯수',num1)


ndarray 메서드의 갯수 56
리스트 메서드의 갯수 45
ndarray 속성의 갯수 15
리스트 속성의 갯수 33


In [157]:
A = np.array([[1,2], [3,4]])
B = np.array([[1,1], [1,1]])
C = A + B
C

array([[2, 3],
       [4, 5]])

In [158]:
A = np.array([[1,2], [3,4], [5,6]])
B = np.array([[2,3], [2,3]])
C = np.matmul(A, B)
C

array([[ 6,  9],
       [14, 21],
       [22, 33]])

In [160]:
numbers = pd.Series([100, 200, 300])
print(numbers)

scores = pd. Series([90,80,99], index=['국어', '수학', '영어'])
print(scores)
print(scores.index)
print(scores.values)
print(scores.index[1], scores.values[1])

0    100
1    200
2    300
dtype: int64
국어    90
수학    80
영어    99
dtype: int64
Index(['국어', '수학', '영어'], dtype='object')
[90 80 99]
수학 80


In [161]:
temperatures = [[3.3, 34.5, 14.2, -10], [7.1, 32.1, 10.7, 2]]
seasons = ['Spring', 'Summer', 'Fall', 'Winter']
regions = ['Seoul', 'Pusan']

data = pd.DataFrame(temperatures, index=regions, columns=seasons)

print(data)
print("=" * 50)
print(data.index)
print(data.values)
print("=" * 50)

print(data['Spring']['Seoul'])
print("=" * 50)

print(data.tail(1))

       Spring  Summer  Fall  Winter
Seoul     3.3    34.5  14.2     -10
Pusan     7.1    32.1  10.7       2
Index(['Seoul', 'Pusan'], dtype='object')
[[  3.3  34.5  14.2 -10. ]
 [  7.1  32.1  10.7   2. ]]
3.3
       Spring  Summer  Fall  Winter
Pusan     7.1    32.1  10.7       2
